.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PENERATOR" "1" "May 2018" "nabijaczleweli" ""
.
.SH "NAME"
\fBpenerator\fR \- Generate a secure password over your local network
.
.SH "SYNOPSIS"
\fBpenerator\fR \fIOPTIONS\fR
.
.SH "DESCRIPTION"
Generate a secure password over your local network\.
.
.SH "OPTIONS"
[TODO]
.
.SH "AUTHOR"
Written by nabijaczleweli <\fInabijaczleweli@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/nabijaczleweli/penerator/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/nabijaczleweli/penerator\fR>
